name: new_project_1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  table_calendar: ^3.0.9
  intl: ^0.20.0
  cloud_firestore: ^5.6.12  # db
  cloud_functions: ^5.5.0  # firebase functions 이용을 위함
  firebase_auth: ^5.7.0    # 인증을 위함
  firebase_core: ^3.13.0   # firebase 이용을 위함
  firebase_storage: ^12.4.10 # 갤러리에서 사진선택 했을 때 DB에 자장할 때 사용. _민서
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_slidable: ^3.0.0
  naver_login_sdk: ^3.0.1  # naver login sdk로 쉽게 로직을 짬._찬홍 
  flutter_native_splash: ^2.4.6 # 앱 로팅화면  구현할 때 사용. _ 가령 
  auto_size_text: ^3.0.0 #설문 조사 할떄 질문이 도형을 넘지 못하게 자동으로 맞춰줄 때 사용. _가령
  image_picker: ^1.0.4 #프로필 사진 변경할 떄 갤러리로 넘어갈 때 사용. _민서
  shared_preferences: ^2.0.15 #심리테스트 결과 불러올 때 사용. _민서
  permission_handler: ^12.0.1 #갤러리 권한 요청할 떄 사용. _민서

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  

flutter:
  uses-material-design: true


  assets:
    - assets/images/LoginHome/LoadingLogo.png
    - assets/images/LoginHome/Logo.png
    - assets/images/LoginHome/talk1.png
    - assets/images/LoginHome/talk2.png
    - assets/images/LoginHome/talk3.png

    - assets/images/mainpage/friend_on.png
    - assets/images/mainpage/friend_off.png
    - assets/images/mainpage/home_on.png
    - assets/images/mainpage/home_off.png
    - assets/images/mainpage/timetable_on.png
    - assets/images/mainpage/timetable_off.png
    - assets/images/mainpage/setting.png
    - assets/images/mainpage/notifications.png
    - assets/images/mainpage/delete.png

    - assets/images/Notification/calendar.png
    - assets/images/Notification/friend.png
    - assets/images/Notification/title.png

    - assets/images/friendScreen/star_on.png
    - assets/images/friendScreen/star_off.png
    - assets/images/PsychologyTest/Character/ch1_1.png
    - assets/images/PsychologyTest/Character/ch1_2.png
    - assets/images/PsychologyTest/Character/ch1_3.png
    - assets/images/PsychologyTest/Character/ch1_4.png
    - assets/images/PsychologyTest/Character/ch2_1.png
    - assets/images/PsychologyTest/Character/ch2_2.png
    - assets/images/PsychologyTest/Character/ch2_3.png
    - assets/images/PsychologyTest/Character/ch2_4.png
    - assets/images/PsychologyTest/Character/QuestionMark.png
    - assets/images/PsychologyTest/Character/TestStart_Character.png

    - assets/images/PsychologyTest/Shape/Rectangle1-1.png
    - assets/images/PsychologyTest/Shape/Rectangle1-2.png
    - assets/images/PsychologyTest/Shape/Rectangle1-3.png
    - assets/images/PsychologyTest/Shape/Rectangle1-4.png
    - assets/images/PsychologyTest/Shape/Rectangle2-1.png
    - assets/images/PsychologyTest/Shape/Rectangle2-2.png
    - assets/images/PsychologyTest/Shape/Rectangle2-3.png
    - assets/images/PsychologyTest/Shape/Rectangle2-4.png

    - assets/images/PsychologyTest/Shape/Ellipse.png
    - assets/images/PsychologyTest/Shape/Polygon.png
    - assets/images/PsychologyTest/Shape/Star.png
    

    - assets/images/Setting/
    - assets/images/Setting/Exclude.png
    - assets/images/Setting/Subtract.png
    - assets/images/Setting/gallery.png
    - assets/images/Setting/Union.png
    - assets/images/Setting/chac1.png
    - assets/images/Setting/chac2.png
    - assets/images/Setting/chac3.png
    - assets/images/Setting/chac4.png
    - assets/images/Setting/chac5.png
    - assets/images/Setting/chac6.png
    - assets/images/Setting/chac7.png
    - assets/images/Setting/chac8.png

  fonts:
    - family: League Spartan
      fonts:

        - asset: assets/fonts/LeagueSpartan-VariableFont_wght.ttf
          weight: 700
    - family: Golos Text
      fonts:
        - asset: assets/fonts/GolosText-VariableFont_wght.ttf
          weight: 500
        - asset: assets/fonts/GolosText-Bold.ttf
          weight: 800
