name: new_project_1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  cloud_firestore: ^5.6.7  # db
  cloud_functions: ^5.5.0  # firebase functions 이용을 위함
  firebase_auth: ^5.5.3    # 인증을 위함
  firebase_core: ^3.13.0   # firebase 이용을 위함
  flutter:
    sdk: flutter
  naver_login_sdk: ^3.0.1  # naver login sdk로 쉽게 로직을 짬._찬홍 
  flutter_native_splash: ^2.4.6 # 앱 로팅화면  구현할 때 사용. _ 가령 
  auto_size_text: ^3.0.0 #설문 조사 할떄 질문이 도형을 넘지 못하게 자동으로 맞춰줄 때 사용. _가령



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  

flutter:
  uses-material-design: true


  assets:
    - assets/images/Logo.png
    - assets/images/talk1.png
    - assets/images/talk2.png
    - assets/images/talk3.png
    - assets/images/1_1.png
    - assets/images/1_2.png
    - assets/images/1_3.png
    - assets/images/1_4.png
    - assets/images/2_1.png
    - assets/images/2_2.png
    - assets/images/2_3.png
    - assets/images/2_4.png
    - assets/images/ch1_1.png
    - assets/images/ch1_2.png
    - assets/images/ch1_3.png
    - assets/images/ch1_4.png
    - assets/images/ch2_1.png
    - assets/images/ch2_2.png
    - assets/images/ch2_3.png
    - assets/images/ch2_4.png
    - assets/images/TestLoading.png
    - assets/images/Star.png
    - assets/images/Polygon.png
    - assets/images/Ellipse.png
    - assets/images/mainpage/home.png
    - assets/images/mainpage/friend.png
    - assets/images/mainpage/callender.png
  


  fonts:
    - family: League Spartan
      fonts:

        - asset: assets/fonts/LeagueSpartan-VariableFont_wght.ttf
          weight: 700
    - family: Golos Text
      fonts:
        - asset: assets/fonts/GolosText-VariableFont_wght.ttf
          weight: 500
